wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691986359.333398
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      - 105
      3:
      - 2
      - 23
      4: 3.9.12
      5: 0.15.8
      6: 4.17.0
      8:
      - 3
      - 5
